### ISSUE TITLE
python-glanceclient updated to latest one during setup-everything.yml

### ISSUE THREAD

**Issue by bjoernt** [rcbops/ansible-lxc-rpc#473] opened 2014-11-05 20:30 UTC
Altough git_install_branch was set to 0.13.1 at /opt/ansible-lxc-rpc/rpc_deployment# grep git_install_branch vars/repo_packages/python_glanceclient.yml I found container which had the version updated to 0.14.1

That needs to be checked out 

root@626973-Infra02_utility_container-a4823739:~# pip list |grep glance
python-glanceclient (0.14.1)

**Comment by bjoernt** [comment] 2014-11-05 20:41
Mitigated this issue while adding 

export OS_IMAGE_URL=http://<internal_vip>:9292

in the openrc of the utility and glance container

**Comment by claco** [comment] 2014-11-05 20:43
Adding some reference material.

First, as of right now, stable/icehouse, 9.0.0, and 9.0.1 all have 0.13.1 in the python_glanceclient.yml

This happened in this changeset: https://github.com/rcbops/ansible-lxc-rpc/pull/122, which seemed to close: https://github.com/rcbops/ansible-lxc-rpc/issues/113

Now in master, proposed/juno, this commit bumped that dep to 0.14.1:  https://github.com/rcbops/ansible-lxc-rpc/pull/234

However, the original bug is not fixed upstream: https://bugs.launchpad.net/python-glanceclient/+bug/1367782

Using the glanceclient in the utilities container doesn't use the internal url. This is likely because a) the upstream bug in 0.14.0/1, and b) the fact that we also don't drop anything image specific in the openrc template (like OS_IMAGE_URL=http://172.28.236.10:9292 or GLANCE_ENDPOINT_TYPE (no effect it seems)

Seems like we should either rollback the version to 0.13.1, and/or update the openrc. Since the upstream package isn't fixed, seems like a regression compared to 9.0.0.

/cc @cloudnull @andymcc @mattt416 for further nuance details.

**Comment by bjoernt** [comment] 2014-11-06 02:16
We see those issues for nova, neutron too there is something bigger broken

**Comment by claco** [comment] 2014-11-06 17:55
Slowly gathering info from Paris folks.

In terms of master, proposed/juno, 10.0.0 will likely release with this as a known issue. Juno requires newer versions that are just broken in this way until upstream makes a new release. Hopefully, this release will happen in time for the impending 10.1.0 release.

As for a 9.0.x install, I'm not sure why any code in that version, hitting the stable/icehouse folders should be installing 0.14.1 since the version in the yml is 0.13.1.

**Comment by Bumblebee-Man** [comment] 2014-11-06 19:52
As Bjoern stated, this appears to be affecting other clients:

utility_container:~# pip list | egrep 'neutron|nova|keystone|glance'
python-glanceclient (0.14.1)
python-keystoneclient (0.11.1)
python-neutronclient (2.3.9)
python-novaclient (2.20.0)

grep git_install_branch python_*
python_neutronclient.yml:git_install_branch: 2.3.6
python_novaclient.yml:git_install_branch: 2.18.1
python_keystoneclient.yml:git_install_branch: 0.10.1
python_glanceclient.yml:git_install_branch: 0.13.1

**Comment by sigmavirus24** [comment] 2014-11-06 21:41
So as best as I can tell this is due to there being both 0.13.1 and 0.14.1 (and the same goes for the other clients) in the directory of wheels built for 9.0.x. This means that when pip tries to install the dependencies (which are not pinned when declared) it finds the latest version and installs that instead. There are two possible approaches:
- pin the dependencies in ansible (either where they're declared or somewhere central)
- clean up slushee to remove old versions

**Comment by cloudnull** [comment] 2014-11-06 21:50
@sigmavirus24 is exactly correct, the 9.0.1 release has multiple version of the same file in it which was due to us not managing the repos correctly early on. That said this has been fixed, however not pushed to slushee, it is however in "http://rpc.cloudnull.io/python_packages/9.0.1/". I can go about flushing / pruning the slushee repo here in a bit to solve this.

**Comment by claco** [comment] 2014-11-06 22:48
Current plan: ensureing the 9.0.x folders have the right versions in the repo. Will deal with the rpc_release variable in 9.0.2, and support tomorrow to get things back in order.

**Comment by bjoernt** [comment] 2014-11-07 00:13
OK sounds good, how are we going to fix the existing container ? Rebuilding them ?

**Comment by cloudnull** [comment] 2014-11-07 03:32
As a status update, I was going to do the cleanup sooner however I've had issues with Hotel internet while traveling however it's all now been done. All of the py repos are pushed and everything back up to cloudfiles.  While the change is online now we are now awaiting the regeneration of the index from the rax cdn so things should be well enough in a few hours.

**Comment by cloudnull** [comment] 2014-11-07 03:44
@BjoernT to fix the clients that have been installed that are known to be bad I'd recommend simply uninstalling the clients via ansbile and then re-installing them.

Example for `python-glanceclient`

``` bash
PACKAGE_NAME="python-glanceclient"
ansible 'hosts:all_containers' -m shell -a "if pip freeze | grep ${PACKAGE_NAME};then pip uninstall -y ${PACKAGE_NAME} && pip install ${PACKAGE_NAME}; fi"
```

This process should be able to rapidly resolve any issues with any client package that may have been installed incorrectly in the past.

**Comment by claco** [comment] 2014-11-07 03:59
@cloudnull in the cpanel for that container, I see the updates in 9.0.1, but there is no 9.0.2.

**Comment by cloudnull** [comment] 2014-11-07 04:22
@claco Sadly we are awaiting the refreshing of the cloudfiles index. If you go to the URL directly it'll load and for the purpose of deployments it should be all good to go. The two new folders that are online are "http://rpc-slushee.rackspace.com/python_packages/9.0.2/" and "http://rpc-slushee.rackspace.com/python_packages/10.0.0rc3/". If for some reason cloudfiles takes longer than normal to refresh we can use "http://rpc.cloudnull.io/python_packages/" which is the source for the objects in cloudfiles.

**Comment by claco** [comment] 2014-11-07 04:22
Do you even sleep bro? :-P Speaking of rpc.cloudnull.io, do you have, can you make it, an ansible playbook that sets up that server from scratch, so any of us can have one to dev/tinker with?

**Comment by cloudnull** [comment] 2014-11-07 04:36
Sleep if for the weak... :) 

I have a hacked up bastardization of a self deployment playbook for the repo bits. I'll clean it up and put it somewhere for all to enjoy. 

Also sticking with the theme surrounding glance here are all of the glance packages that are online in slushee. 

``` bash
| d69a58f12bafcffe8b128bedddbd8698 | 2014-11-07T03:11:55.417960 | 83050      | python_packages/pools/python_glanceclient-0.14.1-py2.py3-none-any.whl                                                                       | application/octet-stream      |
| f79c0cd87545dc891ef3862642e559b5 | 2014-11-07T03:11:51.001730 | 81143      | python_packages/pools/python_glanceclient-0.13.1-py2.py3-none-any.whl                                                                       | application/octet-stream      |
| d41d8cd98f00b204e9800998ecf8427e | 2014-11-07T04:15:09.311890 | 0          | python_packages/9.0.0/python_glanceclient-0.13.1-py2.py3-none-any.whl                                                                       | application/octet-stream      |
| d41d8cd98f00b204e9800998ecf8427e | 2014-11-07T04:16:57.329270 | 0          | python_packages/10.0.0rc1/python_glanceclient-0.14.1-py2.py3-none-any.whl                                                                   | application/octet-stream      |
| d41d8cd98f00b204e9800998ecf8427e | 2014-11-07T04:16:38.298550 | 0          | python_packages/master/python_glanceclient-0.14.1-py2.py3-none-any.whl                                                                      | application/octet-stream      |
| d41d8cd98f00b204e9800998ecf8427e | 2014-11-07T04:15:01.623170 | 0          | python_packages/stable/icehouse/python_glanceclient-0.13.1-py2.py3-none-any.whl                                                             | application/octet-stream      |
| d41d8cd98f00b204e9800998ecf8427e | 2014-11-07T04:15:36.755920 | 0          | python_packages/10.0.0rc3/python_glanceclient-0.14.1-py2.py3-none-any.whl                                                                   | application/octet-stream      |
| d41d8cd98f00b204e9800998ecf8427e | 2014-11-07T04:16:41.768540 | 0          | python_packages/proposed/juno/python_glanceclient-0.14.1-py2.py3-none-any.whl                                                               | application/octet-stream      |
| d41d8cd98f00b204e9800998ecf8427e | 2014-11-07T04:16:29.316330 | 0          | python_packages/10.0.0rc2/python_glanceclient-0.14.1-py2.py3-none-any.whl                                                                   | application/octet-stream      |
| d41d8cd98f00b204e9800998ecf8427e | 2014-11-07T04:15:23.237300 | 0          | python_packages/9.0.2/python_glanceclient-0.13.1-py2.py3-none-any.whl                                                                       | application/octet-stream      |
| d41d8cd98f00b204e9800998ecf8427e | 2014-11-07T04:16:01.932150 | 0          | python_packages/9.0.1/python_glanceclient-0.13.1-py2.py3-none-any.whl                                                                       | application/octet-stream      |
```

Note the 0 bite size for most of the files. This is because the distribution files are all links that point back to the real object in the pools directory. This should make things cleaner and consume a lot less storage.

**Comment by bjoernt** [comment] 2014-11-07 17:07
We probably should update the rpc_repo_version to 9.0.1 for 9.0.1 and newer builds ?

inventory/group_vars/all.yml still set to 9.0.0

Also a pip uninstall and install will trigger the installation of the latest version of the python clients, looking into that because it blocks my install

**Comment by bjoernt** [comment] 2014-11-07 17:14
slushee repo 9.0.1 seem to have issues

```
Skipping link http://rpc-slushee.rackspace.com/python_packages/9.0.1/xattr-0.7.5-cp27-none-linux_x86_64.whl (from http://rpc-slushee.rackspace.com/python_packages/9.0.1/); wrong project name (not python-keystoneclient)
Skipping link http://rpc-slushee.rackspace.com/python_packages/9.0.1/zake-0.1.6-py2-none-any.whl (from http://rpc-slushee.rackspace.com/python_packages/9.0.1/); wrong project name (not python-keystoneclient)
```

  Using version 0.11.1 (newest of versions: 0.11.1, 0.10.1)
  HTTP error 404 while getting http://rpc-slushee.rackspace.com/python_packages/9.0.1/python_keystoneclient-0.11.1-py2.py3-none-any.whl (from http://rpc-slushee.rackspace.com/python_packages/9.0.1/)
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/local/lib/python2.7/dist-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/usr/local/lib/python2.7/dist-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 547, in unpack_http_url
    resp.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/models.py", line 795, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found

**Comment by bjoernt** [comment] 2014-11-07 17:31
Looks like automatically picks up the latest versions and tries to install it. The 9.0 version has multiple cinder client versions and that's why 9.0.0 is working opposed to 9.0.1. Since we are not giving a specific version to install as python-XXclient it seem to pick the latest:
failed: [Infra02_cinder_api_container-492f1609] => (item=python-cinderclient) => {"attempts": 3, "cmd": "/usr/local/bin/pip install --allow-all-external python-cinderclient", "failed": true, "item": "python-cinderclient"}
msg: Task failed as maximum retries was encountered
failed: [Infra02_cinder_api_container-492f1609] => (item=python-keystoneclient) => {"attempts": 3, "cmd": "/usr/local/bin/pip install --allow-all-external python-keystoneclient", "failed": true, "item": "python-keystoneclient"}
msg: Task failed as maximum retries was encountered
failed: [Infra02_cinder_api_container-492f1609] => (item=keystonemiddleware) => {"attempts": 3, "cmd": "/usr/local/bin/pip install --allow-all-external keystonemiddleware", "failed": true, "item": "keystonemiddleware"}

**Comment by bjoernt** [comment] 2014-11-07 17:59
@cloudnull  @claco 
PACKAGE_NAME="python-glanceclient"
ansible 'hosts:all_containers' -m shell -a "if pip freeze | grep ${PACKAGE_NAME};then pip uninstall -y ${PACKAGE_NAME} && pip install ${PACKAGE_NAME}; fi"

is only temporary fix, a rerun of playbooks upgrades the packages again

**Comment by cloudnull** [comment] 2014-11-07 18:04
@BjoernT  are you installing Icehouse or Juno? from the looks of the output it looks like you're running the Juno glance patch?

**Comment by cloudnull** [comment] 2014-11-07 18:17
@BjoernT @claco - the slushee repo is fixed in the sense that the packages that we have online are all of the correct ones and that everything is being hosted as we've intended it too.  Last night all of the abnormalities with the slushee repo were fixed. Specifically, the only glance client that we are allowing for 9.0.1 is "python_glanceclient-0.13.1-py2.py3-none-any.whl" and the keystone client is "python_keystoneclient-0.11.2-py2.py3-none-any.whl" which is what we've spec't out.All that said, we are in a state of limbo waiting for the repo indexes to update from some internal process within cloudfiles and this process can up to two weeks.  For an imediate test and fix please use "http://rpc.cloudnull.io" which will become packages on "https://mirror.rackspace.com". This change over will happen VERY soon allowing us to NEVER have these problems EVER again but in the mean time to get the deployment done and consistent I'd recommend the switch.  Should the slushee repo indexes get updated between the time you read this and try the install again you can by all means continue using it as there should be no further issues once the indexes are squared away.

**Comment by bjoernt** [comment] 2014-11-07 18:21
@cloudnull Icehouse

**Comment by cloudnull** [comment] 2014-11-17 15:26
Closing this issue as the new version of the glance client has been updated in our deployment as well as released by upstream glance which fixes these issues.

**Closed as completed by cloudnull** 2014-11-17 15:26 UTC
Labels: bug, qe, regression, expedite, prio:1
