### ISSUE TITLE
[rsyslog] ppa timeout

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/ansible-lxc-rpc#463] opened 2014-11-04 17:07 UTC
```
TASK: [container_common | Add Container repos] ******************************** 
ok: [node92_rsyslog_container-407d4b48] => (item={'repo': 'ppa:adiscon/v8-stable', 'state': 'present'})
ok: [node116_rsyslog_container-be62eb77] => (item={'repo': 'ppa:adiscon/v8-stable', 'state': 'present'})
failed: [node113_rsyslog_container-c2880889] => (item={'repo': 'ppa:adiscon/v8-stable', 'state': 'present'}) => {"failed": true, "item": {"repo": "ppa:adiscon/v8-stable", "state": "present"}, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "<stdin>", line 2071, in <module>
  File "<stdin>", line 408, in main
  File "<stdin>", line 343, in add_source
  File "<stdin>", line 322, in _get_ppa_info
  File "<stdin>", line 2058, in fetch_url
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
ssl.SSLError: The read operation timed out

failed: [node120_rsyslog_container-86e4232e] => (item={'repo': 'ppa:adiscon/v8-stable', 'state': 'present'}) => {"failed": true, "item": {"repo": "ppa:adiscon/v8-stable", "state": "present"}, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "<stdin>", line 2071, in <module>
  File "<stdin>", line 408, in main
  File "<stdin>", line 343, in add_source
  File "<stdin>", line 322, in _get_ppa_info
  File "<stdin>", line 2058, in fetch_url
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
ssl.SSLError: The read operation timed out

failed: [node101_rsyslog_container-5cd88aad] => (item={'repo': 'ppa:adiscon/v8-stable', 'state': 'present'}) => {"failed": true, "item": {"repo": "ppa:adiscon/v8-stable", "state": "present"}, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "<stdin>", line 2071, in <module>
  File "<stdin>", line 408, in main
  File "<stdin>", line 343, in add_source
  File "<stdin>", line 322, in _get_ppa_info
  File "<stdin>", line 2058, in fetch_url
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
ssl.SSLError: The read operation timed out

failed: [node89_rsyslog_container-d246092a] => (item={'repo': 'ppa:adiscon/v8-stable', 'state': 'present'}) => {"failed": true, "item": {"repo": "ppa:adiscon/v8-stable", "state": "present"}, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "<stdin>", line 2071, in <module>
  File "<stdin>", line 408, in main
  File "<stdin>", line 343, in add_source
  File "<stdin>", line 322, in _get_ppa_info
  File "<stdin>", line 2058, in fetch_url
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
ssl.SSLError: The read operation timed out

failed: [node94_rsyslog_container-48b77ab6] => (item={'repo': 'ppa:adiscon/v8-stable', 'state': 'present'}) => {"failed": true, "item": {"repo": "ppa:adiscon/v8-stable", "state": "present"}, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "<stdin>", line 2071, in <module>
  File "<stdin>", line 408, in main
  File "<stdin>", line 343, in add_source
  File "<stdin>", line 322, in _get_ppa_info
  File "<stdin>", line 2058, in fetch_url
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
ssl.SSLError: The read operation timed out
```

Saw a ppa timeout on a package that we are installing for rsyslog, reran with the --limit and no timeouts this time i just want to raise this issue so we can track this repo timing out

**Comment by hughsaunders** [comment] 2014-11-06 21:18
Duplicate of #445 ?

**Comment by b3rn4rd0s** [comment] 2014-11-13 16:21
Closing due to dup of #445 .

**Closed as completed** 2014-11-13 16:22 UTC
Labels: qe
